accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name= 'logout'),
    path('signup/', views.signUp, name = 'signup')
]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.landing, name = 'landing')
]

storySession/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def login_view(request):
    error = 'Please Enter A Correct Username and or Password'
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home:landing')
    else:
        form = AuthenticationForm()
    response = {
        'form': form,
        'error': error
    }
    return render(request, 'accounts/login.html', response)

def logout_view(request):
    user = request.user
    if user.is_authenticated:
        logout(request)
        return redirect('home:landing')
    return redirect('accounts:login')

def signUp(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home:landing')
    else:
        form = UserCreationForm()
    response = {
        'form': form
    }
    return render(request, 'accounts/signup.html', response)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def landing(request):
    return render(request, 'home/landing.html')

templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %} <link rel="stylesheet" href="{% static 'css/login.css' %}"> {% endblock %}
 
{% block title %} Login {% endblock %}

{% block content %}       

    <div class="title-container">
        <p>
            Login
        </p>
    </div>

    <div class="form-container">
        <form action="{% url 'accounts:login' %}" method = 'post' id = 'form'>
            {% csrf_token %}
            <div class="form-wrapper">
                <div class="username-container">
                    <p>
                        Username: 
                    </p>

                    {{ form.username }}
                </div>

                <div class="password-container">
                    <p>
                        Password:
                    </p>

                    {{ form.password }}
                </div>

                <div class="button-container">
                    <input type="submit" value="Login" id = 'login-button'>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %} <link rel="stylesheet" href="{% static 'css/signup.css' %}"> {% endblock %}
{% block title %} Sign Up {% endblock %}

{% block content %}

    <div class="form-container">
        <form action="{% url 'accounts:signup' %}" method = 'post'>
            {% csrf_token %}

            <div class="form-wrapper">
                <div class="username-container">
                    <p>
                        Username: 
                    </p>

                    {{ form.username }}

                    <p class = 'helptext'>
                        Required 150 Characters or fewer. Letters, digits, and @/./+/-/_ only.
                    </p>
                </div>

                <div class="password-container">
                    <p>
                        Password:
                    </p>

                    {{ form.password1 }}

                    <p class = 'helptext'>
                        <ul>
                            <li> Your Password can't be too similar to your oter personal information </li>
                            <li> Your Password must contain at least 8 characters </li>
                            <li> Your Password can't be a commonly used password </li>
                            <li> Your password cant'be entirely numeric </li>
                        </ul>
                    </p>
                </div>

                <div class="password-container">
                    <p>
                        Password Confirmation:
                    </p>

                    {{ form.password2 }}
                </div>
            </div>


            <!-- {{ form }} -->

            <input type="submit" value="Sign Up">
        </form>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial -scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        {% block style %} {% endblock %}
        
        <title> {% block title %} {% endblock %} </title>
    </head>

    <body>
        {% block content %}
        {% endblock %}

    </body>
</html>

templates/home/landing.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %} <link rel="stylesheet" href="{% static 'css/landing.css' %}"> {% endblock %}
{% block title %} Welcome {% endblock %}

{% block content %}
    <div class="page-container">

        <div class="navbar-container">
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li id="logout-button"> <a href="{% url 'accounts:logout' %}"> Logout </a> </li>
                    {% else %}
                        <li id = 'login-button'> <a href="{% url 'accounts:login' %}"> Login </a> </li>
                        <li id = 'signup-button'> <a href="{% url 'accounts:signup' %}"> Sign Up </a> </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    
        <div class="title-container">
            <h1>
                Welcome To The Website
            </h1>
    
            {% if user.is_authenticated %}
                <h2>
                    How are you doing, {{ user.username }} ?
                </h2>
            {% endif %}
        </div>
    </div>

{% endblock %}